[package]
name = "render-pipeline-shaders"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { git = "https://github.com/projectkml/ash" }
bitflags = "2.0.0-rc.1"
paste = "1.0.11"
render-pipeline-shaders-sys = { path = "render-pipeline-shaders-sys" }
libc = "0.2.138"
libloading = "0.7.4"
static_assertions = "1.1.0"

[features]
default = ["vulkan"]
d3d11 = ["render-pipeline-shaders-sys/d3d11"]
d3d12 = ["render-pipeline-shaders-sys/d3d12"]
vulkan = ["render-pipeline-shaders-sys/vulkan"]

