[package]
name = "rps-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0+1.3.281"

[build-dependencies]
bindgen = "0.69.4"
cc = "1.0.90"

[features]
d3d11 = []
d3d12 = []
vulkan = []

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
